{% set name = "dkimpy" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://launchpad.net/dkimpy/1.1/{{ version }}/+download/{{ name }}-{{ version }}.tar.gz
  sha256: b5f60fb47bbf5d8d762f134bcea0c388eba6b498342a682a21f1686545094b77

build:
  entry_points:
    - arcsign = dkim.arcsign:main
    - arcverify = dkim.arcverify:main
    - dkimsign = dkim.dkimsign:main
    - dkimverify = dkim.dkimverify:main
    - dknewkey = dkim.dknewkey:main
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5
    - dnspython >=2.0.0
    - authres
    - pynacl
    - aiodns

test:
  imports:
    - dkim
  commands:
    - pip check
    - dkimsign --help
    - dkimverify --help
    - dknewkey --help
  requires:
    - pip

about:
  home: https://launchpad.net/dkimpy
  summary: 'DomainKeys Identified Mail email signing and verification'
  description: |
    dkimpy is a library that implements DKIM (DomainKeys Identified Mail), ARC
    (Authenticated Receive Chain), and TLSRPT (TLS Report) email signing and
    verification. Basic DKIM requirements are defined in RFC 6376:

    https://tools.ietf.org/html/rfc6376
  license: 0BSD
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pymilter.org/pydkim/
  dev_url: https://git.launchpad.net/dkimpy

extra:
  recipe-maintainers:
    - blmaier
